In [1]:
import numpy as np 
import cv2 
import matplotlib.pyplot as plt
import PIL.Image as Image
import rasterio as rio
import gym
import random

from gym import Env, spaces
import time

import matplotlib.patches as patches

from model import *

from torchvision import models, transforms

from earth_env import *

from IPython import display

font = cv2.FONT_HERSHEY_COMPLEX_SMALL 

torch.autograd.set_detect_anomaly(True)

In [4]:
env = EarthObs(num_channels = 3, num_actions = 5)
obs = env.reset()

# last_screen = env.get_screen()
current_screen = env.get_screen()

memory = ReplayMemory(10000)

# while True:

done = False

while not done:

    # Select and perform an action
    action = env.select_action()

    # Save current state so we can push it to memory in a couple lines
    current_state = env.view_box.clip_image(cv2.imread("./test_image.png"))

    _, reward, done, _ = env.step(action.item())

    next_state = env.view_box.clip_image(cv2.imread("./test_image.png"))

    memory.push(current_state, action, next_state, reward)

    print(action)

    env.render()

    # Perform one step of the optimization (on the policy network)
    env.optimize_model()


env.close()

/Users/heatherbaier/opt/anaconda3/envs/dhsrl/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float16
  logger.warn(


Random action!
Migration Loss:  420.4695129394531
Select!
moved:  620 476
Migration Loss:  420.4695129394531
t1 pred:  tensor([[-0.4695]], grad_fn=<AddmmBackward>)   |  t2 pred:  tensor([[-0.4695]], grad_fn=<AddmmBackward>)   |  reward:  0
tensor([[4]])
Optimizing model!
Random action!
Migration Loss:  420.4695129394531
moved:  620 508
Migration Loss:  420.3634338378906
t1 pred:  tensor([[-0.4695]], grad_fn=<AddmmBackward>)   |  t2 pred:  tensor([[-0.3634]], grad_fn=<AddmmBackward>)   |  reward:  10
tensor([[1]])
Optimizing model!
Random action!
Migration Loss:  420.3634338378906
moved:  652 508
Migration Loss:  420.1523742675781
t1 pred:  tensor([[-0.3634]], grad_fn=<AddmmBackward>)   |  t2 pred:  tensor([[-0.1524]], grad_fn=<AddmmBackward>)   |  reward:  10
tensor([[2]])
Optimizing model!
Random action!
Migration Loss:  414.4007568359375
Select!
moved:  652 508
Migration Loss:  414.4007568359375
t1 pred:  tensor([[5.5992]], grad_fn=<AddmmBackward>)   |  t2 pred:  tensor([[5.5992]], g